/**
 * Integration tests for proof functions: groth16_setup → prove → verify.
 *
 * These tests are SLOW: groth16_setup performs a full Groth16 trusted setup
 * which takes several minutes. Run only when needed.
 *
 *   npm run build && npm test
 *
 * The mock input is loaded from mock_proof_input.json (generated by zkap-circuit
 * integration tests).
 */

import test from 'ava'
import { existsSync, writeFileSync, mkdtempSync } from 'node:fs'
import { resolve, join } from 'node:path'
import { tmpdir } from 'node:os'

// Skip manifest.json CRS integrity check in tests — pk is generated in-memory
// and no generate_crs manifest exists in the temp directory.
process.env['ZKAP_SKIP_MANIFEST_CHECK'] = '1'

// ---------------------------------------------------------------------------
// Guard: skip if binary not built
// ---------------------------------------------------------------------------
const PACKAGE_ROOT = resolve(import.meta.dirname ?? __dirname, '..')
const INDEX_JS = resolve(PACKAGE_ROOT, 'index.js')
const MOCK_INPUT = resolve(PACKAGE_ROOT, '__test__/mock_proof_input.json')

const binaryMissing = !existsSync(INDEX_JS)
if (binaryMissing) {
  console.warn('[proof.spec.ts] Native binary not found. Skipping all tests.')
}

const bindings = binaryMissing ? null : await import(INDEX_JS)
const groth16Setup = bindings?.groth16Setup
const prove = bindings?.prove
const verify = bindings?.verify

const it = binaryMissing ? test.skip : test

// ---------------------------------------------------------------------------
// Load mock input
// ---------------------------------------------------------------------------
const mock = JSON.parse(
  (await import('node:fs')).readFileSync(MOCK_INPUT, 'utf8')
)

const CONFIG = {
  maxJwtB64Len: mock.max_jwt_b64_len,
  maxPayloadB64Len: mock.max_payload_b64_len,
  maxAudLen: mock.max_aud_len,
  maxExpLen: mock.max_exp_len,
  maxIssLen: mock.max_iss_len,
  maxNonceLen: mock.max_nonce_len,
  maxSubLen: mock.max_sub_len,
  n: mock.n,
  k: mock.k,
  treeHeight: mock.tree_height,
  numAudienceLimit: mock.num_audience_limit,
  claims: mock.claims,
  forbiddenString: mock.forbidden_string,
}

// ---------------------------------------------------------------------------
// groth16_setup
// ---------------------------------------------------------------------------

it('groth16_setup: returns non-empty pk_bytes and vk_bytes', async (t) => {
  t.timeout(600_000) // 10 min — setup is slow
  const output = await groth16Setup(CONFIG)
  t.true(output.pkBytes instanceof Uint8Array, 'pkBytes should be Uint8Array')
  t.true(output.vkBytes instanceof Uint8Array, 'vkBytes should be Uint8Array')
  t.true(output.pkBytes.length > 0, 'pkBytes should not be empty')
  t.true(output.vkBytes.length > 0, 'vkBytes should not be empty')
})

// ---------------------------------------------------------------------------
// prove + verify (end-to-end)
// ---------------------------------------------------------------------------

it('prove + verify: generates valid proof from mock input', async (t) => {
  t.timeout(600_000) // 10 min

  // 1. Setup
  const setup = await groth16Setup(CONFIG)

  // 2. Write pk + manifest to temp dir (prove checks for manifest.json beside pk)
  const tmpDir = mkdtempSync(join(tmpdir(), 'zkap-test-'))
  const pkPath = join(tmpDir, 'pk.bin')
  writeFileSync(pkPath, Buffer.from(setup.pkBytes))
  // manifest.json must match CONFIG params exactly
  writeFileSync(join(tmpDir, 'manifest.json'), JSON.stringify({
    profile: 'test',
    params: {
      MAX_JWT_B64_LEN: CONFIG.maxJwtB64Len,
      MAX_PAYLOAD_B64_LEN: CONFIG.maxPayloadB64Len,
      MAX_AUD_LEN: CONFIG.maxAudLen,
      MAX_EXP_LEN: CONFIG.maxExpLen,
      MAX_ISS_LEN: CONFIG.maxIssLen,
      MAX_NONCE_LEN: CONFIG.maxNonceLen,
      MAX_SUB_LEN: CONFIG.maxSubLen,
      N: CONFIG.n,
      K: CONFIG.k,
      TREE_HEIGHT: CONFIG.treeHeight,
      NUM_AUDIENCE_LIMIT: CONFIG.numAudienceLimit,
    },
  }))

  // 3. Prove
  const request = {
    pkPath,
    jwts: mock.jwts,
    pkOps: mock.pk_ops,
    merklePaths: mock.merkle_paths,
    leafIndices: mock.leaf_indices,
    root: mock.root,
    anchor: mock.anchor,
    hSignUserOp: mock.h_sign_user_op,
    random: mock.random,
    audList: mock.aud_list,
  }

  const proofOutput = await prove(CONFIG, request)

  t.true(Array.isArray(proofOutput.proofs), 'proofs should be an array')
  t.true(proofOutput.proofs.length > 0, 'should produce at least one proof')
  t.true(Array.isArray(proofOutput.publicInputs), 'publicInputs should be an array')
  t.is(proofOutput.proofs.length, proofOutput.publicInputs.length, 'proofs and publicInputs lengths match')

  // 4. Verify all k proofs
  for (let i = 0; i < proofOutput.proofs.length; i++) {
    const isValid = await verify(
      setup.vkBytes,
      proofOutput.proofs[i],
      proofOutput.publicInputs[i],
    )
    t.true(isValid, `proof[${i}] should verify as valid`)
  }
})

it('verify: rejects tampered proof bytes', async (t) => {
  t.timeout(600_000)

  const setup = await groth16Setup(CONFIG)

  const tmpDir = mkdtempSync(join(tmpdir(), 'zkap-test-'))
  const pkPath = join(tmpDir, 'pk.bin')
  writeFileSync(pkPath, Buffer.from(setup.pkBytes))
  writeFileSync(join(tmpDir, 'manifest.json'), JSON.stringify({
    profile: 'test',
    params: {
      MAX_JWT_B64_LEN: CONFIG.maxJwtB64Len, MAX_PAYLOAD_B64_LEN: CONFIG.maxPayloadB64Len,
      MAX_AUD_LEN: CONFIG.maxAudLen, MAX_EXP_LEN: CONFIG.maxExpLen, MAX_ISS_LEN: CONFIG.maxIssLen,
      MAX_NONCE_LEN: CONFIG.maxNonceLen, MAX_SUB_LEN: CONFIG.maxSubLen,
      N: CONFIG.n, K: CONFIG.k, TREE_HEIGHT: CONFIG.treeHeight, NUM_AUDIENCE_LIMIT: CONFIG.numAudienceLimit,
    },
  }))

  const request = {
    pkPath,
    jwts: mock.jwts,
    pkOps: mock.pk_ops,
    merklePaths: mock.merkle_paths,
    leafIndices: mock.leaf_indices,
    root: mock.root,
    anchor: mock.anchor,
    hSignUserOp: mock.h_sign_user_op,
    random: mock.random,
    audList: mock.aud_list,
  }

  const proofOutput = await prove(CONFIG, request)

  // Flip a byte in each proof to corrupt it.
  // A tampered proof must either return false or throw a deserialization error —
  // both are acceptable rejection outcomes.
  for (let i = 0; i < proofOutput.proofs.length; i++) {
    const tampered = Buffer.from(proofOutput.proofs[i])
    tampered[tampered.length - 1] ^= 0xff

    let accepted = false
    try {
      accepted = await verify(setup.vkBytes, tampered, proofOutput.publicInputs[i])
    } catch {
      // Deserialization error on corrupted bytes is a valid rejection
      accepted = false
    }
    t.false(accepted, `tampered proof[${i}] should not be accepted`)
  }
})
