require 'json'

package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'ZkapSdkModule'
  s.version        = package['version']
  s.summary        = package['description']
  s.license        = package['license']
  s.authors        = package['author']
  s.homepage       = package['homepage']
  s.platform       = :ios, '15.0'
  s.swift_version  = '5.9'
  s.source         = { git: package['repository']['url'] }

  s.source_files   = ['ZkapSdkModule.swift', 'uniffi/**/*.{swift,h,m}']

  # Pre-built Rust static libraries (generated by CI build-react-native.yml)
  s.vendored_frameworks = 'ZkapZkp.xcframework'

  # Expose C headers for the Rust FFI symbols (UniFFI-generated module)
  s.preserve_paths = 'uniffi/*.h'
  s.xcconfig = {
    'OTHER_LDFLAGS' => '-lc++'
  }

  s.dependency 'ExpoModulesCore'

  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'SWIFT_COMPILATION_MODE' => 'wholemodule',
    'HEADER_SEARCH_PATHS' => '$(PODS_TARGET_SRCROOT)/uniffi',
    'OTHER_CFLAGS' => '-fmodule-map-file=$(PODS_TARGET_SRCROOT)/uniffi/zkap_uniffi_bindingsFFI.modulemap'
  }
end
