require 'json'

package = JSON.parse(File.read(File.join(__dir__, '..', 'package.json')))

Pod::Spec.new do |s|
  s.name           = 'ZkapSdkModule'
  s.version        = package['version']
  s.summary        = package['description']
  s.license        = package['license']
  s.authors        = package['author']
  s.homepage       = package['homepage']
  s.platform       = :ios, '15.0'
  s.swift_version  = '5.9'
  s.source         = { git: package['repository']['url'] }

  s.source_files   = 'ios/**/*.{swift,h,m}'

  # Pre-built Rust static libraries (generated by CI build-react-native.yml)
  s.vendored_libraries = 'ios/lib/libzkap_core.a'

  # Expose C headers for the Rust FFI symbols
  s.preserve_paths = 'ios/include/*.h'
  s.xcconfig = {
    'HEADER_SEARCH_PATHS' => '$(PODS_TARGET_SRCROOT)/ios/include',
    'OTHER_LDFLAGS' => '-lc++'
  }

  s.dependency 'ExpoModulesCore'

  s.pod_target_xcconfig = {
    'DEFINES_MODULE' => 'YES',
    'SWIFT_COMPILATION_MODE' => 'wholemodule'
  }
end
