// Generated by uniffi-bindgen-react-native
#ifdef __cplusplus
#import "baerae-zkap-react-native.h"
#endif

#ifdef RCT_NEW_ARCH_ENABLED
#import "ZkapReactNativeSpec.h"

@interface ZkapReactNative : NSObject <NativeZkapReactNativeSpec>
#else
#import <React/RCTBridgeModule.h>

@interface ZkapReactNative : NSObject <RCTBridgeModule>
#endif

@end