// Generated by uniffi-bindgen-react-native
#import "ZkapReactNative.h"
#import <CommonCrypto/CommonDigest.h>
#import <WebKit/WebKit.h>
#import <stdlib.h>

static NSString *ZkapSha256Hex(NSData *data) {
    unsigned char digest[CC_SHA256_DIGEST_LENGTH];
    CC_SHA256(data.bytes, (CC_LONG)data.length, digest);
    NSMutableString *hex = [NSMutableString stringWithCapacity:CC_SHA256_DIGEST_LENGTH * 2];
    for (int i = 0; i < CC_SHA256_DIGEST_LENGTH; i++) {
        [hex appendFormat:@"%02x", digest[i]];
    }
    return hex;
}

static BOOL ZkapReadUInt64(id value, unsigned long long *out) {
    if ([value isKindOfClass:NSNumber.class]) {
        *out = [value unsignedLongLongValue];
        return YES;
    }
    if (![value isKindOfClass:NSString.class]) {
        return NO;
    }

    const char *text = [(NSString *)value UTF8String];
    if (!text || text[0] == '\0') {
        return NO;
    }
    char *end = NULL;
    unsigned long long parsed = strtoull(text, &end, 10);
    if (end == text || *end != '\0') {
        return NO;
    }
    *out = parsed;
    return YES;
}

static BOOL ZkapValidateBase64InputField(NSDictionary *input,
                                         NSString *payloadKey,
                                         NSString *lengthKey,
                                         NSString *shaKey,
                                         NSString **error) {
    NSString *payload = [input[payloadKey] isKindOfClass:NSString.class] ? input[payloadKey] : nil;
    NSString *expectedSha = [input[shaKey] isKindOfClass:NSString.class] ? input[shaKey] : nil;
    unsigned long long expectedLength = 0;
    if (!payload || !expectedSha || !ZkapReadUInt64(input[lengthKey], &expectedLength)) {
        *error = [NSString stringWithFormat:@"invalid WKWebView witness input field %@", payloadKey];
        return NO;
    }

    NSData *decoded = [[NSData alloc] initWithBase64EncodedString:payload options:0];
    if (!decoded) {
        *error = [NSString stringWithFormat:@"invalid WKWebView witness base64 field %@", payloadKey];
        return NO;
    }
    if (decoded.length != expectedLength) {
        *error = [NSString stringWithFormat:@"WKWebView witness input length mismatch for %@", payloadKey];
        return NO;
    }
    NSString *actualSha = ZkapSha256Hex(decoded);
    if ([actualSha caseInsensitiveCompare:expectedSha] != NSOrderedSame) {
        *error = [NSString stringWithFormat:@"WKWebView witness input sha256 mismatch for %@", payloadKey];
        return NO;
    }
    return YES;
}

static BOOL ZkapValidateWitnessInput(NSDictionary *input, NSString **error) {
    return ZkapValidateBase64InputField(input, @"wasm_base64", @"wasm_byte_length", @"witness_gen_sha256", error) &&
        ZkapValidateBase64InputField(input, @"request_json_base64", @"request_json_byte_length", @"request_json_sha256", error) &&
        ZkapValidateBase64InputField(input, @"config_json_base64", @"config_json_byte_length", @"config_json_sha256", error);
}

@class ZkapWitnessRunner;

static NSMutableSet<ZkapWitnessRunner *> *ZkapActiveWitnessRunners() {
    static NSMutableSet<ZkapWitnessRunner *> *runners;
    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        runners = [NSMutableSet new];
    });
    return runners;
}

@interface ZkapWitnessRunner : NSObject <WKScriptMessageHandler, WKNavigationDelegate>
@property (nonatomic, copy) NSString *inputJson;
@property (nonatomic, copy) NSString *runId;
@property (nonatomic, copy) RCTPromiseResolveBlock resolve;
@property (nonatomic, copy) RCTPromiseRejectBlock reject;
@property (nonatomic, strong) WKWebView *webView;
@property (nonatomic, strong) NSMutableDictionary<NSNumber *, NSString *> *chunks;
@property (nonatomic, assign) NSInteger totalChunks;
@property (nonatomic, assign) NSUInteger base64Length;
@property (nonatomic, assign) BOOL finished;
+ (void)runWithInputJson:(NSString *)inputJson
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject;
@end

@implementation ZkapWitnessRunner

+ (void)runWithInputJson:(NSString *)inputJson
                 resolve:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject
{
    dispatch_async(dispatch_get_main_queue(), ^{
        ZkapWitnessRunner *runner = [ZkapWitnessRunner new];
        runner.inputJson = inputJson;
        runner.resolve = resolve;
        runner.reject = reject;
        runner.chunks = [NSMutableDictionary new];
        [runner start];
    });
}

- (void)start
{
    NSError *jsonError = nil;
    NSData *inputData = [self.inputJson dataUsingEncoding:NSUTF8StringEncoding];
    NSDictionary *input = [NSJSONSerialization JSONObjectWithData:inputData options:0 error:&jsonError];
    if (![input isKindOfClass:NSDictionary.class]) {
        [self fail:[NSString stringWithFormat:@"invalid WKWebView witness input: %@", jsonError]];
        return;
    }
    NSString *inputError = nil;
    if (!ZkapValidateWitnessInput(input, &inputError)) {
        [self fail:inputError ?: @"invalid WKWebView witness input"];
        return;
    }
    id runId = input[@"run_id"];
    self.runId = [runId isKindOfClass:NSString.class] ? runId : NSUUID.UUID.UUIDString;

    WKWebViewConfiguration *configuration = [WKWebViewConfiguration new];
    configuration.userContentController = [WKUserContentController new];
    [configuration.userContentController addScriptMessageHandler:self name:@"zkapWitness"];

    self.webView = [[WKWebView alloc] initWithFrame:CGRectZero configuration:configuration];
    self.webView.navigationDelegate = self;
    self.webView.hidden = YES;
    [ZkapActiveWitnessRunners() addObject:self];
    [self.webView loadHTMLString:[self htmlForInputJson:self.inputJson] baseURL:nil];

    __weak ZkapWitnessRunner *weakSelf = self;
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(120 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        ZkapWitnessRunner *strongSelf = weakSelf;
        if (strongSelf && !strongSelf.finished) {
            [strongSelf fail:@"WKWebView witness timed out"];
        }
    });
}

- (NSString *)htmlForInputJson:(NSString *)inputJson
{
    NSData *literalData = [NSJSONSerialization dataWithJSONObject:@[inputJson ?: @""]
                                                          options:0
                                                            error:nil];
    NSString *inputLiteral = [[NSString alloc] initWithData:literalData encoding:NSUTF8StringEncoding];
    NSMutableString *html = [NSMutableString string];
    [html appendString:@"<!doctype html><html><body><script>\n"];
    [html appendString:@"(function(){\n"];
    [html appendString:@"const inputJson = "];
    [html appendString:inputLiteral];
    [html appendString:@"[0];\n"];
    [html appendString:@"const input = JSON.parse(inputJson);\n"];
    [html appendString:@"const runId = input.run_id;\n"];
    [html appendString:@"function post(message){ window.webkit.messageHandlers.zkapWitness.postMessage(message); }\n"];
    [html appendString:@"function fail(error){ const message = ((error && error.message) ? error.message : '') + ((error && error.stack) ? ('\\n' + error.stack) : '') || String(error); post({type:'error', run_id:runId, message}); }\n"];
    [html appendString:@"function b64ToBytes(b64){ const binary = atob(b64); const bytes = new Uint8Array(binary.length); for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i); return bytes; }\n"];
    [html appendString:@"function utf8(bytes){ if (typeof TextDecoder !== 'undefined') return new TextDecoder().decode(bytes); let out = ''; for (let i = 0; i < bytes.length; i++) out += String.fromCharCode(bytes[i]); return out; }\n"];
    [html appendString:@"function bytesToBase64(bytes){ let binary = ''; const step = 0x8000; for (let i = 0; i < bytes.length; i += step) { const slice = bytes.subarray(i, i + step); binary += String.fromCharCode.apply(null, slice); } return btoa(binary); }\n"];
    [html appendString:@"function postBase64Chunks(bytes, chunkSize){ const base64ChunkSize = Math.max(4, Number(chunkSize || 4194304)); let rawChunkSize = Math.floor(base64ChunkSize / 4) * 3; rawChunkSize = Math.max(3, rawChunkSize - (rawChunkSize % 3)); const totalChunks = Math.max(1, Math.ceil(bytes.length / rawChunkSize)); let base64Length = 0; for (let index = 0; index < totalChunks; index++) { const start = index * rawChunkSize; const end = Math.min(bytes.length, start + rawChunkSize); const payload = bytesToBase64(bytes.subarray(start, end)); base64Length += payload.length; post({type:'chunk', run_id:runId, chunk_index:index, total_chunks:totalChunks, chunk_bytes:payload.length, payload_chunk:payload}); } return {totalChunks, base64Length}; }\n"];
    [html appendString:@"async function main(){ const totalStart = performance.now(); const wasmBytes = b64ToBytes(input.wasm_base64); const requestBytes = b64ToBytes(input.request_json_base64); const configBytes = b64ToBytes(input.config_json_base64); const instantiated = await WebAssembly.instantiate(wasmBytes, {}); const instance = instantiated.instance || instantiated; const exports = instance.exports; const memory = exports.memory; if (!memory) throw new Error('wasm export `memory` missing'); const reqPtr = exports.wg_alloc(requestBytes.length); const cfgPtr = exports.wg_alloc(configBytes.length); new Uint8Array(memory.buffer, reqPtr, requestBytes.length).set(requestBytes); new Uint8Array(memory.buffer, cfgPtr, configBytes.length).set(configBytes); const nRaw = exports.synthesize_witness(reqPtr, requestBytes.length, cfgPtr, configBytes.length); const n = typeof nRaw === 'bigint' ? Number(nRaw) : Number(nRaw); exports.wg_dealloc(reqPtr, requestBytes.length); exports.wg_dealloc(cfgPtr, configBytes.length); if (n < 0) { const errPtr = exports.wg_last_error_ptr(); const errLen = exports.wg_last_error_len(); const errBytes = new Uint8Array(memory.buffer, errPtr, errLen).slice(); throw new Error('wasm synthesize_witness reported: ' + utf8(errBytes)); } const outPtr = exports.wg_last_output_ptr(); const output = new Uint8Array(memory.buffer, outPtr, n).slice(); const chunks = postBase64Chunks(output, input.chunk_size); post({type:'done', run_id:runId, byte_length:n, base64_length:chunks.base64Length, total_chunks:chunks.totalChunks, timing_ms:performance.now() - totalStart}); }\n"];
    [html appendString:@"main().catch(fail);\n"];
    [html appendString:@"})();\n"];
    [html appendString:@"</script></body></html>\n"];
    return html;
}

- (void)userContentController:(WKUserContentController *)userContentController didReceiveScriptMessage:(WKScriptMessage *)message
{
    if (self.finished) {
        return;
    }
    NSDictionary *body = [message.body isKindOfClass:NSDictionary.class] ? message.body : nil;
    if (!body) {
        [self fail:@"WKWebView witness sent a non-object message"];
        return;
    }
    NSString *messageRunId = [body[@"run_id"] isKindOfClass:NSString.class] ? body[@"run_id"] : nil;
    if (![messageRunId isEqualToString:self.runId]) {
        [self fail:@"WKWebView witness run_id mismatch"];
        return;
    }
    NSString *type = [body[@"type"] isKindOfClass:NSString.class] ? body[@"type"] : nil;
    if ([type isEqualToString:@"chunk"]) {
        [self handleChunk:body];
    } else if ([type isEqualToString:@"done"]) {
        [self handleDone:body];
    } else if ([type isEqualToString:@"error"]) {
        NSString *errorMessage = [body[@"message"] isKindOfClass:NSString.class] ? body[@"message"] : @"WKWebView witness failed";
        [self fail:errorMessage];
    } else {
        [self fail:@"WKWebView witness sent an unknown message type"];
    }
}

- (void)handleChunk:(NSDictionary *)body
{
    NSNumber *indexNumber = [body[@"chunk_index"] isKindOfClass:NSNumber.class] ? body[@"chunk_index"] : nil;
    NSNumber *totalNumber = [body[@"total_chunks"] isKindOfClass:NSNumber.class] ? body[@"total_chunks"] : nil;
    NSNumber *chunkBytesNumber = [body[@"chunk_bytes"] isKindOfClass:NSNumber.class] ? body[@"chunk_bytes"] : nil;
    NSString *payload = [body[@"payload_chunk"] isKindOfClass:NSString.class] ? body[@"payload_chunk"] : nil;
    if (!indexNumber || !totalNumber || !chunkBytesNumber || !payload) {
        [self fail:@"WKWebView witness chunk is missing required fields"];
        return;
    }

    NSInteger index = indexNumber.integerValue;
    NSInteger total = totalNumber.integerValue;
    if (total <= 0 || index < 0 || index >= total) {
        [self fail:@"WKWebView witness chunk index out of range"];
        return;
    }
    if (self.totalChunks == 0) {
        self.totalChunks = total;
    } else if (self.totalChunks != total) {
        [self fail:@"WKWebView witness total_chunks changed"];
        return;
    }
    NSNumber *key = @(index);
    if (self.chunks[key] != nil) {
        [self fail:@"WKWebView witness sent a duplicate chunk"];
        return;
    }
    if (payload.length != chunkBytesNumber.unsignedIntegerValue) {
        [self fail:@"WKWebView witness chunk length mismatch"];
        return;
    }
    self.chunks[key] = payload;
    self.base64Length += payload.length;
}

- (void)handleDone:(NSDictionary *)body
{
    NSNumber *byteLengthNumber = [body[@"byte_length"] isKindOfClass:NSNumber.class] ? body[@"byte_length"] : nil;
    NSNumber *base64LengthNumber = [body[@"base64_length"] isKindOfClass:NSNumber.class] ? body[@"base64_length"] : nil;
    NSNumber *totalChunksNumber = [body[@"total_chunks"] isKindOfClass:NSNumber.class] ? body[@"total_chunks"] : nil;
    if (!byteLengthNumber || !base64LengthNumber || !totalChunksNumber) {
        [self fail:@"WKWebView witness completion is missing required fields"];
        return;
    }
    NSInteger total = totalChunksNumber.integerValue;
    if (total <= 0 || self.totalChunks != total || self.chunks.count != (NSUInteger)total) {
        [self fail:@"WKWebView witness chunk count mismatch"];
        return;
    }
    NSMutableString *joined = [NSMutableString stringWithCapacity:self.base64Length];
    for (NSInteger i = 0; i < total; i++) {
        NSString *chunk = self.chunks[@(i)];
        if (!chunk) {
            [self fail:@"WKWebView witness missing chunk"];
            return;
        }
        [joined appendString:chunk];
    }
    if (joined.length != base64LengthNumber.unsignedIntegerValue) {
        [self fail:@"WKWebView witness base64 length mismatch"];
        return;
    }

    NSData *decoded = [[NSData alloc] initWithBase64EncodedString:joined options:0];
    if (!decoded || decoded.length != byteLengthNumber.unsignedIntegerValue) {
        [self fail:@"WKWebView witness decoded length mismatch"];
        return;
    }
    NSString *sha256 = ZkapSha256Hex(decoded);
    NSString *fileName = [NSString stringWithFormat:@"zkap-witness-%@.bin", self.runId];
    NSString *witnessPath = [NSTemporaryDirectory() stringByAppendingPathComponent:fileName];
    NSError *writeError = nil;
    if (![decoded writeToFile:witnessPath options:NSDataWritingAtomic error:&writeError]) {
        [self fail:[NSString stringWithFormat:@"WKWebView witness file write failed: %@", writeError.localizedDescription]];
        return;
    }
    NSDictionary *result = @{
        @"witnessBundlePath": witnessPath,
        @"sha256": sha256,
        @"byteLength": @(decoded.length),
        @"base64Length": @(joined.length),
        @"chunkCount": @(total),
        @"timingMs": body[@"timing_ms"] ?: @0,
    };
    NSData *jsonData = [NSJSONSerialization dataWithJSONObject:result options:0 error:nil];
    NSString *json = [[NSString alloc] initWithData:jsonData encoding:NSUTF8StringEncoding];
    self.resolve(json);
    [self finish];
}

- (void)webView:(WKWebView *)webView didFailNavigation:(WKNavigation *)navigation withError:(NSError *)error
{
    [self fail:[NSString stringWithFormat:@"WKWebView witness navigation failed: %@", error.localizedDescription]];
}

- (void)webView:(WKWebView *)webView didFailProvisionalNavigation:(WKNavigation *)navigation withError:(NSError *)error
{
    [self fail:[NSString stringWithFormat:@"WKWebView witness provisional navigation failed: %@", error.localizedDescription]];
}

- (void)fail:(NSString *)message
{
    if (self.finished) {
        return;
    }
    self.reject(@"zkap-witness-webview", message, nil);
    [self finish];
}

- (void)finish
{
    if (self.finished) {
        return;
    }
    self.finished = YES;
    [self.webView.configuration.userContentController removeScriptMessageHandlerForName:@"zkapWitness"];
    self.webView.navigationDelegate = nil;
    [self.webView stopLoading];
    self.webView = nil;
    [ZkapActiveWitnessRunners() removeObject:self];
}

@end

namespace uniffi_generated {
    using namespace facebook::react;
    /**
    * ObjC++ class for module 'NativeZkapReactNative'
    */
    class JSI_EXPORT NativeZkapReactNativeSpecJSI : public ObjCTurboModule {
    public:
        NativeZkapReactNativeSpecJSI(const ObjCTurboModule::InitParams &params);
        std::shared_ptr<CallInvoker> callInvoker;
    };

    static facebook::jsi::Value __hostFunction_ZkapReactNative_installRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        auto& tm = static_cast<NativeZkapReactNativeSpecJSI&>(turboModule);
        auto jsInvoker = tm.callInvoker;
        uint8_t result = baerae_zkapreactnative::installRustCrate(rt, jsInvoker);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_ZkapReactNative_cleanupRustCrate(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        uint8_t result = baerae_zkapreactnative::cleanupRustCrate(rt);
        return facebook::jsi::Value(rt, result);
    }
    static facebook::jsi::Value __hostFunction_ZkapReactNative_runWitnessInWkWebView(facebook::jsi::Runtime& rt, TurboModule &turboModule, const facebook::jsi::Value* args, size_t count) {
        return static_cast<ObjCTurboModule &>(turboModule).invokeObjCMethod(
            rt,
            PromiseKind,
            "runWitnessInWkWebView",
            @selector(runWitnessInWkWebView:resolve:reject:),
            args,
            count);
    }

    NativeZkapReactNativeSpecJSI::NativeZkapReactNativeSpecJSI(const ObjCTurboModule::InitParams &params)
        : ObjCTurboModule(params), callInvoker(params.jsInvoker) {
            this->methodMap_["installRustCrate"] = MethodMetadata {1, __hostFunction_ZkapReactNative_installRustCrate};
            this->methodMap_["cleanupRustCrate"] = MethodMetadata {1, __hostFunction_ZkapReactNative_cleanupRustCrate};
            this->methodMap_["runWitnessInWkWebView"] = MethodMetadata {1, __hostFunction_ZkapReactNative_runWitnessInWkWebView};
    }
} // namespace uniffi_generated

@implementation ZkapReactNative
RCT_EXPORT_MODULE()

// Don't compile this code when we build for the old architecture.
#ifdef RCT_NEW_ARCH_ENABLED

// Automated testing checks baerae_zkapreactnative
// by comparing the whole line here.
/*
- (NSNumber *)multiply:(double)a b:(double)b {
    NSNumber *result = @(baerae_zkapreactnative::multiply(a, b));
}
*/

- (NSNumber *)installRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (NSNumber *)cleanupRustCrate {
    @throw [NSException exceptionWithName:@"UnreachableException"
                        reason:@"This method should never be called."
                        userInfo:nil];
}

- (void)runWitnessInWkWebView:(NSString *)inputJson
                      resolve:(RCTPromiseResolveBlock)resolve
                       reject:(RCTPromiseRejectBlock)reject
{
    [ZkapWitnessRunner runWithInputJson:inputJson resolve:resolve reject:reject];
}

- (std::shared_ptr<facebook::react::TurboModule>)getTurboModule:
    (const facebook::react::ObjCTurboModule::InitParams &)params
{
    return std::make_shared<uniffi_generated::NativeZkapReactNativeSpecJSI>(params);
}
#endif

@end
