// Generated by uniffi-bindgen-react-native
#include "baerae-zkap-react-native.h"
#include "generated/zkap_uniffi_bindings.hpp"

namespace baerae_zkapreactnative {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeZkapUniffiBindings::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		NativeZkapUniffiBindings::unregisterModule(runtime);
		return true;
	}
}
