// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.zkap_uniffi_bindings

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_zkap_uniffi_bindings_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_zkap_uniffi_bindings_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "zkap_uniffi_bindings"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "zkap_uniffi_bindings"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }
    external fun uniffi_zkap_uniffi_bindings_checksum_func_generate_anchor(
    ): Short
    external fun uniffi_zkap_uniffi_bindings_checksum_func_generate_aud_hash(
    ): Short
    external fun uniffi_zkap_uniffi_bindings_checksum_func_generate_hash(
    ): Short
    external fun uniffi_zkap_uniffi_bindings_checksum_func_generate_leaf_hash(
    ): Short
    external fun uniffi_zkap_uniffi_bindings_checksum_func_prove(
    ): Short
    external fun ffi_zkap_uniffi_bindings_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "zkap_uniffi_bindings"))
        
    }
    external fun uniffi_zkap_uniffi_bindings_fn_func_generate_anchor(`config`: RustBuffer.ByValue,`secrets`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_zkap_uniffi_bindings_fn_func_generate_aud_hash(`config`: RustBuffer.ByValue,`audList`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_zkap_uniffi_bindings_fn_func_generate_hash(`messages`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_zkap_uniffi_bindings_fn_func_generate_leaf_hash(`config`: RustBuffer.ByValue,`iss`: RustBuffer.ByValue,`pkB64`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_zkap_uniffi_bindings_fn_func_prove(`config`: RustBuffer.ByValue,`request`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_zkap_uniffi_bindings_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_zkap_uniffi_bindings_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_zkap_uniffi_bindings_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_zkap_uniffi_bindings_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_zkap_uniffi_bindings_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_zkap_uniffi_bindings_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_zkap_uniffi_bindings_checksum_func_generate_anchor() != 10088.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zkap_uniffi_bindings_checksum_func_generate_aud_hash() != 42467.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zkap_uniffi_bindings_checksum_func_generate_hash() != 6188.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zkap_uniffi_bindings_checksum_func_generate_leaf_hash() != 28430.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_zkap_uniffi_bindings_checksum_func_prove() != 26090.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    IntegrityCheckingUniffiLib
    // UniffiLib() initialized as objects are used, but we still need to explicitly
    // reference it so initialization across crates works as expected.
    UniffiLib
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class ZkapAnchorResult (
    var `evaluations`: List<kotlin.String>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapAnchorResult: FfiConverterRustBuffer<ZkapAnchorResult> {
    override fun read(buf: ByteBuffer): ZkapAnchorResult {
        return ZkapAnchorResult(
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: ZkapAnchorResult) = (
            FfiConverterSequenceString.allocationSize(value.`evaluations`)
    )

    override fun write(value: ZkapAnchorResult, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`evaluations`, buf)
    }
}



data class ZkapAudHashResult (
    var `audHashes`: List<kotlin.String>
    , 
    var `hAudList`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapAudHashResult: FfiConverterRustBuffer<ZkapAudHashResult> {
    override fun read(buf: ByteBuffer): ZkapAudHashResult {
        return ZkapAudHashResult(
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ZkapAudHashResult) = (
            FfiConverterSequenceString.allocationSize(value.`audHashes`) +
            FfiConverterString.allocationSize(value.`hAudList`)
    )

    override fun write(value: ZkapAudHashResult, buf: ByteBuffer) {
            FfiConverterSequenceString.write(value.`audHashes`, buf)
            FfiConverterString.write(value.`hAudList`, buf)
    }
}



data class ZkapCircuitConfig (
    var `maxJwtB64Len`: kotlin.ULong
    , 
    var `maxPayloadB64Len`: kotlin.ULong
    , 
    var `maxAudLen`: kotlin.ULong
    , 
    var `maxExpLen`: kotlin.ULong
    , 
    var `maxIssLen`: kotlin.ULong
    , 
    var `maxNonceLen`: kotlin.ULong
    , 
    var `maxSubLen`: kotlin.ULong
    , 
    var `n`: kotlin.ULong
    , 
    var `k`: kotlin.ULong
    , 
    var `treeHeight`: kotlin.ULong
    , 
    var `numAudienceLimit`: kotlin.ULong
    , 
    var `claims`: List<kotlin.String>
    , 
    var `forbiddenString`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapCircuitConfig: FfiConverterRustBuffer<ZkapCircuitConfig> {
    override fun read(buf: ByteBuffer): ZkapCircuitConfig {
        return ZkapCircuitConfig(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ZkapCircuitConfig) = (
            FfiConverterULong.allocationSize(value.`maxJwtB64Len`) +
            FfiConverterULong.allocationSize(value.`maxPayloadB64Len`) +
            FfiConverterULong.allocationSize(value.`maxAudLen`) +
            FfiConverterULong.allocationSize(value.`maxExpLen`) +
            FfiConverterULong.allocationSize(value.`maxIssLen`) +
            FfiConverterULong.allocationSize(value.`maxNonceLen`) +
            FfiConverterULong.allocationSize(value.`maxSubLen`) +
            FfiConverterULong.allocationSize(value.`n`) +
            FfiConverterULong.allocationSize(value.`k`) +
            FfiConverterULong.allocationSize(value.`treeHeight`) +
            FfiConverterULong.allocationSize(value.`numAudienceLimit`) +
            FfiConverterSequenceString.allocationSize(value.`claims`) +
            FfiConverterString.allocationSize(value.`forbiddenString`)
    )

    override fun write(value: ZkapCircuitConfig, buf: ByteBuffer) {
            FfiConverterULong.write(value.`maxJwtB64Len`, buf)
            FfiConverterULong.write(value.`maxPayloadB64Len`, buf)
            FfiConverterULong.write(value.`maxAudLen`, buf)
            FfiConverterULong.write(value.`maxExpLen`, buf)
            FfiConverterULong.write(value.`maxIssLen`, buf)
            FfiConverterULong.write(value.`maxNonceLen`, buf)
            FfiConverterULong.write(value.`maxSubLen`, buf)
            FfiConverterULong.write(value.`n`, buf)
            FfiConverterULong.write(value.`k`, buf)
            FfiConverterULong.write(value.`treeHeight`, buf)
            FfiConverterULong.write(value.`numAudienceLimit`, buf)
            FfiConverterSequenceString.write(value.`claims`, buf)
            FfiConverterString.write(value.`forbiddenString`, buf)
    }
}



data class ZkapProofOutput (
    /**
     * Solidity-compatible proof components per credential: [ax, ay, bx_c1, bx_c0, by_c1, by_c0, cx, cy]
     */
    var `proofs`: List<List<kotlin.String>>
    , 
    var `sharedInputs`: List<kotlin.String>
    , 
    var `partialRhsList`: List<kotlin.String>
    , 
    var `jwtExpList`: List<kotlin.String>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapProofOutput: FfiConverterRustBuffer<ZkapProofOutput> {
    override fun read(buf: ByteBuffer): ZkapProofOutput {
        return ZkapProofOutput(
            FfiConverterSequenceSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: ZkapProofOutput) = (
            FfiConverterSequenceSequenceString.allocationSize(value.`proofs`) +
            FfiConverterSequenceString.allocationSize(value.`sharedInputs`) +
            FfiConverterSequenceString.allocationSize(value.`partialRhsList`) +
            FfiConverterSequenceString.allocationSize(value.`jwtExpList`)
    )

    override fun write(value: ZkapProofOutput, buf: ByteBuffer) {
            FfiConverterSequenceSequenceString.write(value.`proofs`, buf)
            FfiConverterSequenceString.write(value.`sharedInputs`, buf)
            FfiConverterSequenceString.write(value.`partialRhsList`, buf)
            FfiConverterSequenceString.write(value.`jwtExpList`, buf)
    }
}



data class ZkapProofRequest (
    var `pkPath`: kotlin.String
    , 
    var `jwts`: List<kotlin.String>
    , 
    var `pkOps`: List<kotlin.String>
    , 
    var `merklePaths`: List<List<kotlin.String>>
    , 
    var `leafIndices`: List<kotlin.ULong>
    , 
    var `root`: kotlin.String
    , 
    var `anchorEvals`: List<kotlin.String>
    , 
    var `hanchor`: kotlin.String
    , 
    var `hSignUserOp`: kotlin.String
    , 
    var `random`: kotlin.String
    , 
    var `audHashList`: List<kotlin.String>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapProofRequest: FfiConverterRustBuffer<ZkapProofRequest> {
    override fun read(buf: ByteBuffer): ZkapProofRequest {
        return ZkapProofRequest(
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterSequenceSequenceString.read(buf),
            FfiConverterSequenceULong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterSequenceString.read(buf),
        )
    }

    override fun allocationSize(value: ZkapProofRequest) = (
            FfiConverterString.allocationSize(value.`pkPath`) +
            FfiConverterSequenceString.allocationSize(value.`jwts`) +
            FfiConverterSequenceString.allocationSize(value.`pkOps`) +
            FfiConverterSequenceSequenceString.allocationSize(value.`merklePaths`) +
            FfiConverterSequenceULong.allocationSize(value.`leafIndices`) +
            FfiConverterString.allocationSize(value.`root`) +
            FfiConverterSequenceString.allocationSize(value.`anchorEvals`) +
            FfiConverterString.allocationSize(value.`hanchor`) +
            FfiConverterString.allocationSize(value.`hSignUserOp`) +
            FfiConverterString.allocationSize(value.`random`) +
            FfiConverterSequenceString.allocationSize(value.`audHashList`)
    )

    override fun write(value: ZkapProofRequest, buf: ByteBuffer) {
            FfiConverterString.write(value.`pkPath`, buf)
            FfiConverterSequenceString.write(value.`jwts`, buf)
            FfiConverterSequenceString.write(value.`pkOps`, buf)
            FfiConverterSequenceSequenceString.write(value.`merklePaths`, buf)
            FfiConverterSequenceULong.write(value.`leafIndices`, buf)
            FfiConverterString.write(value.`root`, buf)
            FfiConverterSequenceString.write(value.`anchorEvals`, buf)
            FfiConverterString.write(value.`hanchor`, buf)
            FfiConverterString.write(value.`hSignUserOp`, buf)
            FfiConverterString.write(value.`random`, buf)
            FfiConverterSequenceString.write(value.`audHashList`, buf)
    }
}



data class ZkapSecret (
    var `sub`: kotlin.String
    , 
    var `iss`: kotlin.String
    , 
    var `aud`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapSecret: FfiConverterRustBuffer<ZkapSecret> {
    override fun read(buf: ByteBuffer): ZkapSecret {
        return ZkapSecret(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: ZkapSecret) = (
            FfiConverterString.allocationSize(value.`sub`) +
            FfiConverterString.allocationSize(value.`iss`) +
            FfiConverterString.allocationSize(value.`aud`)
    )

    override fun write(value: ZkapSecret, buf: ByteBuffer) {
            FfiConverterString.write(value.`sub`, buf)
            FfiConverterString.write(value.`iss`, buf)
            FfiConverterString.write(value.`aud`, buf)
    }
}





sealed class ZkapException: kotlin.Exception() {
    
    class ApplicationException(
        
        val `message`: kotlin.String
        ) : ZkapException() {
        override val message
            get() = "message=${ `message` }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ZkapException> {
        override fun lift(error_buf: RustBuffer.ByValue): ZkapException = FfiConverterTypeZkapError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeZkapError : FfiConverterRustBuffer<ZkapException> {
    override fun read(buf: ByteBuffer): ZkapException {
        

        return when(buf.getInt()) {
            1 -> ZkapException.ApplicationException(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ZkapException): ULong {
        return when(value) {
            is ZkapException.ApplicationException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`message`)
            )
        }
    }

    override fun write(value: ZkapException, buf: ByteBuffer) {
        when(value) {
            is ZkapException.ApplicationException -> {
                buf.putInt(1)
                FfiConverterString.write(value.`message`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




/**
 * @suppress
 */
public object FfiConverterSequenceULong: FfiConverterRustBuffer<List<kotlin.ULong>> {
    override fun read(buf: ByteBuffer): List<kotlin.ULong> {
        val len = buf.getInt()
        return List<kotlin.ULong>(len) {
            FfiConverterULong.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.ULong>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterULong.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.ULong>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterULong.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceString: FfiConverterRustBuffer<List<kotlin.String>> {
    override fun read(buf: ByteBuffer): List<kotlin.String> {
        val len = buf.getInt()
        return List<kotlin.String>(len) {
            FfiConverterString.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.String>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.String>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterString.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeZkapSecret: FfiConverterRustBuffer<List<ZkapSecret>> {
    override fun read(buf: ByteBuffer): List<ZkapSecret> {
        val len = buf.getInt()
        return List<ZkapSecret>(len) {
            FfiConverterTypeZkapSecret.read(buf)
        }
    }

    override fun allocationSize(value: List<ZkapSecret>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeZkapSecret.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<ZkapSecret>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeZkapSecret.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceSequenceString: FfiConverterRustBuffer<List<List<kotlin.String>>> {
    override fun read(buf: ByteBuffer): List<List<kotlin.String>> {
        val len = buf.getInt()
        return List<List<kotlin.String>>(len) {
            FfiConverterSequenceString.read(buf)
        }
    }

    override fun allocationSize(value: List<List<kotlin.String>>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterSequenceString.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<List<kotlin.String>>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterSequenceString.write(it, buf)
        }
    }
}
        /**
         * Generate a Poseidon threshold anchor from a list of JWT credential secrets.
         */
    @Throws(ZkapException::class) fun `generateAnchor`(`config`: ZkapCircuitConfig, `secrets`: List<ZkapSecret>): ZkapAnchorResult {
            return FfiConverterTypeZkapAnchorResult.lift(
    uniffiRustCallWithError(ZkapException) { _status ->
    UniffiLib.uniffi_zkap_uniffi_bindings_fn_func_generate_anchor(
    
        FfiConverterTypeZkapCircuitConfig.lower(`config`),FfiConverterSequenceTypeZkapSecret.lower(`secrets`),_status)
}
    )
    }
    

        /**
         * Compute per-audience hashes and the combined audience-list hash.
         */
    @Throws(ZkapException::class) fun `generateAudHash`(`config`: ZkapCircuitConfig, `audList`: List<kotlin.String>): ZkapAudHashResult {
            return FfiConverterTypeZkapAudHashResult.lift(
    uniffiRustCallWithError(ZkapException) { _status ->
    UniffiLib.uniffi_zkap_uniffi_bindings_fn_func_generate_aud_hash(
    
        FfiConverterTypeZkapCircuitConfig.lower(`config`),FfiConverterSequenceString.lower(`audList`),_status)
}
    )
    }
    

        /**
         * Compute a Poseidon hash of one or more field-element strings (hex or decimal).
         *
         * Returns the result as a 0x-prefixed hex string.
         */
    @Throws(ZkapException::class) fun `generateHash`(`messages`: List<kotlin.String>): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZkapException) { _status ->
    UniffiLib.uniffi_zkap_uniffi_bindings_fn_func_generate_hash(
    
        FfiConverterSequenceString.lower(`messages`),_status)
}
    )
    }
    

        /**
         * Compute the Merkle leaf hash for an issuer + RSA public-key modulus (base64-encoded).
         *
         * Returns the leaf field element as a 0x-prefixed hex string.
         */
    @Throws(ZkapException::class) fun `generateLeafHash`(`config`: ZkapCircuitConfig, `iss`: kotlin.String, `pkB64`: kotlin.String): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCallWithError(ZkapException) { _status ->
    UniffiLib.uniffi_zkap_uniffi_bindings_fn_func_generate_leaf_hash(
    
        FfiConverterTypeZkapCircuitConfig.lower(`config`),FfiConverterString.lower(`iss`),FfiConverterString.lower(`pkB64`),_status)
}
    )
    }
    

        /**
         * Generate Groth16 proofs from raw user inputs.
         */
    @Throws(ZkapException::class) fun `prove`(`config`: ZkapCircuitConfig, `request`: ZkapProofRequest): ZkapProofOutput {
            return FfiConverterTypeZkapProofOutput.lift(
    uniffiRustCallWithError(ZkapException) { _status ->
    UniffiLib.uniffi_zkap_uniffi_bindings_fn_func_prove(
    
        FfiConverterTypeZkapCircuitConfig.lower(`config`),FfiConverterTypeZkapProofRequest.lower(`request`),_status)
}
    )
    }
    


