/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS-friendly representation of a JWT credential triple. */
export interface JsSecret {
  sub: string
  iss: string
  aud: string
}
/**
 * JS-friendly representation of CircuitConfig.
 *
 * All u64 fields are exposed as f64 (JS number) via napi-rs automatic coercion.
 * `claims` is a list of claim name strings; `forbidden_string` is the padding sentinel.
 */
export interface JsCircuitConfig {
  maxJwtB64Len: number
  maxPayloadB64Len: number
  maxAudLen: number
  maxExpLen: number
  maxIssLen: number
  maxNonceLen: number
  maxSubLen: number
  n: number
  k: number
  treeHeight: number
  numAudienceLimit: number
  claims: Array<string>
  forbiddenString: string
}
/**
 * Compute a Poseidon hash of one or more field-element strings (hex or decimal).
 *
 * Returns the result as a 0x-prefixed hex string.
 */
export declare function generateHash(messages: Array<string>): string
/** Result of `generate_anchor`: the polynomial evaluation points of the anchor. */
export interface JsAnchorResult {
  /** Each evaluation point of the anchor polynomial, as a 0x-prefixed hex string. */
  evaluations: Array<string>
}
/**
 * Generate a Poseidon threshold anchor from a list of JWT credential secrets.
 *
 * Returns the anchor polynomial evaluations as hex strings.
 */
export declare function generateAnchor(config: JsCircuitConfig, secrets: Array<JsSecret>): JsAnchorResult
/** Result of `generate_aud_hash`. */
export interface JsAudHashResult {
  /** Per-audience Poseidon hashes, one per slot (including padding), as hex strings. */
  audHashes: Array<string>
  /** Combined audience-list hash as a hex string. */
  hAudList: string
}
/** Compute per-audience hashes and the combined audience-list hash. */
export declare function generateAudHash(config: JsCircuitConfig, audList: Array<string>): JsAudHashResult
/**
 * Compute the Merkle leaf hash for an issuer + RSA public-key modulus (base64-encoded).
 *
 * Returns the leaf field element as a 0x-prefixed hex string.
 */
export declare function generateLeafHash(config: JsCircuitConfig, iss: string, pkB64: string): string
export declare function groth16Setup(configJson: string): string
export declare function prove(requestJson: string): string
export declare function verify(proofJson: string): boolean
