/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** JS-friendly representation of a JWT credential triple. */
export interface JsSecret {
  sub: string
  iss: string
  aud: string
}
/**
 * JS-friendly representation of CircuitConfig.
 *
 * All u64 fields are exposed as f64 (JS number) via napi-rs automatic coercion.
 * `claims` is a list of claim name strings; `forbidden_string` is the padding sentinel.
 */
export interface JsCircuitConfig {
  maxJwtB64Len: number
  maxPayloadB64Len: number
  maxAudLen: number
  maxExpLen: number
  maxIssLen: number
  maxNonceLen: number
  maxSubLen: number
  n: number
  k: number
  treeHeight: number
  numAudienceLimit: number
  claims: Array<string>
  forbiddenString: string
}
/**
 * Compute a Poseidon hash of one or more field-element strings (hex or decimal).
 *
 * Returns the result as a 0x-prefixed hex string.
 */
export declare function generateHash(messages: Array<string>): string
/** Result of `generate_anchor`: the polynomial evaluation points of the anchor. */
export interface JsAnchorResult {
  /** Each evaluation point of the anchor polynomial, as a 0x-prefixed hex string. */
  evaluations: Array<string>
}
/**
 * Generate a Poseidon threshold anchor from a list of JWT credential secrets.
 *
 * Returns the anchor polynomial evaluations as hex strings.
 */
export declare function generateAnchor(config: JsCircuitConfig, secrets: Array<JsSecret>): JsAnchorResult
/** Result of `generate_aud_hash`. */
export interface JsAudHashResult {
  /** Per-audience Poseidon hashes, one per slot (including padding), as hex strings. */
  audHashes: Array<string>
  /** Combined audience-list hash as a hex string. */
  hAudList: string
}
/** Compute per-audience hashes and the combined audience-list hash. */
export declare function generateAudHash(config: JsCircuitConfig, audList: Array<string>): JsAudHashResult
/**
 * Compute the Merkle leaf hash for an issuer + RSA public-key modulus (base64-encoded).
 *
 * Returns the leaf field element as a 0x-prefixed hex string.
 */
export declare function generateLeafHash(config: JsCircuitConfig, iss: string, pkB64: string): string
/** Output of `groth16_setup`: serialized proving key and verifying key bytes. */
export interface JsSetupOutput {
  /** `ark_serialize` bytes of the Groth16 proving key (Node.js Buffer). */
  pkBytes: Buffer
  /** `ark_serialize` bytes of the Groth16 verifying key (Node.js Buffer). */
  vkBytes: Buffer
}
/** Raw proof request passed from JavaScript to `prove`. */
export interface JsProofRequest {
  /** Path to the proving key file on disk. */
  pkPath: string
  /** JWT tokens — one per credential (must have exactly `k` entries). */
  jwts: Array<string>
  /** RSA public key moduli in Base64 — one per JWT. */
  pkOps: Array<string>
  /** Merkle authentication paths — one Vec per JWT. */
  merklePaths: Array<Array<string>>
  /** Merkle leaf indices — one per JWT. */
  leafIndices: Array<number>
  /** Merkle root as a hex/decimal field-element string. */
  root: string
  /** Anchor polynomial evaluations plus `hanchor` as the last element. */
  anchor: Array<string>
  /** Signed UserOperation hash. */
  hSignUserOp: string
  /** Random blinding value. */
  random: string
  /** Allowed audience values as hex/decimal field-element strings. */
  audList: Array<string>
}
/** Output of `prove`: serialized proof bytes and hex-encoded public inputs per proof. */
export interface JsProofOutput {
  /** `ark_serialize` bytes for each generated Groth16 proof (Node.js Buffer per proof). */
  proofs: Array<Buffer>
  /** Public inputs per proof, each field element as a 0x-prefixed hex string. */
  publicInputs: Array<Array<string>>
}
/**
 * Perform a Groth16 trusted setup for the ZKAP circuit.
 *
 * Returns serialized proving key and verifying key bytes (ark_serialize format).
 * These bytes can be written to disk and later passed to `prove` / `verify`.
 */
export declare function groth16Setup(config: JsCircuitConfig): JsSetupOutput
/**
 * Generate Groth16 proofs from raw user inputs.
 *
 * Returns serialized proof bytes and hex-encoded public inputs for each JWT token.
 */
export declare function prove(config: JsCircuitConfig, request: JsProofRequest): JsProofOutput
/**
 * Verify a single Groth16 proof.
 *
 * - `vk_bytes`: ark_serialize bytes of the verifying key (from `groth16_setup`).
 * - `proof_bytes`: ark_serialize bytes of the proof (from `prove`).
 * - `public_inputs`: field elements as 0x-prefixed hex strings.
 *
 * Returns `true` if the proof is valid.
 */
export declare function verify(vkBytes: Buffer, proofBytes: Buffer, publicInputs: Array<string>): boolean
