// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(zkap_uniffi_bindingsFFI)
import zkap_uniffi_bindingsFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zkap_uniffi_bindings_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zkap_uniffi_bindings_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureZkapUniffiBindingsInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}


public struct ZkapAnchorResult: Equatable, Hashable {
    public var evaluations: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(evaluations: [String]) {
        self.evaluations = evaluations
    }

    

    
}

#if compiler(>=6)
extension ZkapAnchorResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapAnchorResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapAnchorResult {
        return
            try ZkapAnchorResult(
                evaluations: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ZkapAnchorResult, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.evaluations, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapAnchorResult_lift(_ buf: RustBuffer) throws -> ZkapAnchorResult {
    return try FfiConverterTypeZkapAnchorResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapAnchorResult_lower(_ value: ZkapAnchorResult) -> RustBuffer {
    return FfiConverterTypeZkapAnchorResult.lower(value)
}


public struct ZkapAudHashResult: Equatable, Hashable {
    public var audHashes: [String]
    public var hAudList: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(audHashes: [String], hAudList: String) {
        self.audHashes = audHashes
        self.hAudList = hAudList
    }

    

    
}

#if compiler(>=6)
extension ZkapAudHashResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapAudHashResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapAudHashResult {
        return
            try ZkapAudHashResult(
                audHashes: FfiConverterSequenceString.read(from: &buf), 
                hAudList: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ZkapAudHashResult, into buf: inout [UInt8]) {
        FfiConverterSequenceString.write(value.audHashes, into: &buf)
        FfiConverterString.write(value.hAudList, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapAudHashResult_lift(_ buf: RustBuffer) throws -> ZkapAudHashResult {
    return try FfiConverterTypeZkapAudHashResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapAudHashResult_lower(_ value: ZkapAudHashResult) -> RustBuffer {
    return FfiConverterTypeZkapAudHashResult.lower(value)
}


public struct ZkapCircuitConfig: Equatable, Hashable {
    public var maxJwtB64Len: UInt64
    public var maxPayloadB64Len: UInt64
    public var maxAudLen: UInt64
    public var maxExpLen: UInt64
    public var maxIssLen: UInt64
    public var maxNonceLen: UInt64
    public var maxSubLen: UInt64
    public var n: UInt64
    public var k: UInt64
    public var treeHeight: UInt64
    public var numAudienceLimit: UInt64
    public var claims: [String]
    public var forbiddenString: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(maxJwtB64Len: UInt64, maxPayloadB64Len: UInt64, maxAudLen: UInt64, maxExpLen: UInt64, maxIssLen: UInt64, maxNonceLen: UInt64, maxSubLen: UInt64, n: UInt64, k: UInt64, treeHeight: UInt64, numAudienceLimit: UInt64, claims: [String], forbiddenString: String) {
        self.maxJwtB64Len = maxJwtB64Len
        self.maxPayloadB64Len = maxPayloadB64Len
        self.maxAudLen = maxAudLen
        self.maxExpLen = maxExpLen
        self.maxIssLen = maxIssLen
        self.maxNonceLen = maxNonceLen
        self.maxSubLen = maxSubLen
        self.n = n
        self.k = k
        self.treeHeight = treeHeight
        self.numAudienceLimit = numAudienceLimit
        self.claims = claims
        self.forbiddenString = forbiddenString
    }

    

    
}

#if compiler(>=6)
extension ZkapCircuitConfig: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapCircuitConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapCircuitConfig {
        return
            try ZkapCircuitConfig(
                maxJwtB64Len: FfiConverterUInt64.read(from: &buf), 
                maxPayloadB64Len: FfiConverterUInt64.read(from: &buf), 
                maxAudLen: FfiConverterUInt64.read(from: &buf), 
                maxExpLen: FfiConverterUInt64.read(from: &buf), 
                maxIssLen: FfiConverterUInt64.read(from: &buf), 
                maxNonceLen: FfiConverterUInt64.read(from: &buf), 
                maxSubLen: FfiConverterUInt64.read(from: &buf), 
                n: FfiConverterUInt64.read(from: &buf), 
                k: FfiConverterUInt64.read(from: &buf), 
                treeHeight: FfiConverterUInt64.read(from: &buf), 
                numAudienceLimit: FfiConverterUInt64.read(from: &buf), 
                claims: FfiConverterSequenceString.read(from: &buf), 
                forbiddenString: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ZkapCircuitConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.maxJwtB64Len, into: &buf)
        FfiConverterUInt64.write(value.maxPayloadB64Len, into: &buf)
        FfiConverterUInt64.write(value.maxAudLen, into: &buf)
        FfiConverterUInt64.write(value.maxExpLen, into: &buf)
        FfiConverterUInt64.write(value.maxIssLen, into: &buf)
        FfiConverterUInt64.write(value.maxNonceLen, into: &buf)
        FfiConverterUInt64.write(value.maxSubLen, into: &buf)
        FfiConverterUInt64.write(value.n, into: &buf)
        FfiConverterUInt64.write(value.k, into: &buf)
        FfiConverterUInt64.write(value.treeHeight, into: &buf)
        FfiConverterUInt64.write(value.numAudienceLimit, into: &buf)
        FfiConverterSequenceString.write(value.claims, into: &buf)
        FfiConverterString.write(value.forbiddenString, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapCircuitConfig_lift(_ buf: RustBuffer) throws -> ZkapCircuitConfig {
    return try FfiConverterTypeZkapCircuitConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapCircuitConfig_lower(_ value: ZkapCircuitConfig) -> RustBuffer {
    return FfiConverterTypeZkapCircuitConfig.lower(value)
}


public struct ZkapProofOutput: Equatable, Hashable {
    /**
     * Solidity-compatible proof components per credential: [ax, ay, bx_c1, bx_c0, by_c1, by_c0, cx, cy]
     */
    public var proofs: [[String]]
    public var sharedInputs: [String]
    public var partialRhsList: [String]
    public var jwtExpList: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Solidity-compatible proof components per credential: [ax, ay, bx_c1, bx_c0, by_c1, by_c0, cx, cy]
         */proofs: [[String]], sharedInputs: [String], partialRhsList: [String], jwtExpList: [String]) {
        self.proofs = proofs
        self.sharedInputs = sharedInputs
        self.partialRhsList = partialRhsList
        self.jwtExpList = jwtExpList
    }

    

    
}

#if compiler(>=6)
extension ZkapProofOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapProofOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapProofOutput {
        return
            try ZkapProofOutput(
                proofs: FfiConverterSequenceSequenceString.read(from: &buf), 
                sharedInputs: FfiConverterSequenceString.read(from: &buf), 
                partialRhsList: FfiConverterSequenceString.read(from: &buf), 
                jwtExpList: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ZkapProofOutput, into buf: inout [UInt8]) {
        FfiConverterSequenceSequenceString.write(value.proofs, into: &buf)
        FfiConverterSequenceString.write(value.sharedInputs, into: &buf)
        FfiConverterSequenceString.write(value.partialRhsList, into: &buf)
        FfiConverterSequenceString.write(value.jwtExpList, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapProofOutput_lift(_ buf: RustBuffer) throws -> ZkapProofOutput {
    return try FfiConverterTypeZkapProofOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapProofOutput_lower(_ value: ZkapProofOutput) -> RustBuffer {
    return FfiConverterTypeZkapProofOutput.lower(value)
}


public struct ZkapProofRequest: Equatable, Hashable {
    public var pkPath: String
    public var jwts: [String]
    public var pkOps: [String]
    public var merklePaths: [[String]]
    public var leafIndices: [UInt64]
    public var root: String
    public var anchorEvals: [String]
    public var hanchor: String
    public var hSignUserOp: String
    public var random: String
    public var audHashList: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(pkPath: String, jwts: [String], pkOps: [String], merklePaths: [[String]], leafIndices: [UInt64], root: String, anchorEvals: [String], hanchor: String, hSignUserOp: String, random: String, audHashList: [String]) {
        self.pkPath = pkPath
        self.jwts = jwts
        self.pkOps = pkOps
        self.merklePaths = merklePaths
        self.leafIndices = leafIndices
        self.root = root
        self.anchorEvals = anchorEvals
        self.hanchor = hanchor
        self.hSignUserOp = hSignUserOp
        self.random = random
        self.audHashList = audHashList
    }

    

    
}

#if compiler(>=6)
extension ZkapProofRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapProofRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapProofRequest {
        return
            try ZkapProofRequest(
                pkPath: FfiConverterString.read(from: &buf), 
                jwts: FfiConverterSequenceString.read(from: &buf), 
                pkOps: FfiConverterSequenceString.read(from: &buf), 
                merklePaths: FfiConverterSequenceSequenceString.read(from: &buf), 
                leafIndices: FfiConverterSequenceUInt64.read(from: &buf), 
                root: FfiConverterString.read(from: &buf), 
                anchorEvals: FfiConverterSequenceString.read(from: &buf), 
                hanchor: FfiConverterString.read(from: &buf), 
                hSignUserOp: FfiConverterString.read(from: &buf), 
                random: FfiConverterString.read(from: &buf), 
                audHashList: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: ZkapProofRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.pkPath, into: &buf)
        FfiConverterSequenceString.write(value.jwts, into: &buf)
        FfiConverterSequenceString.write(value.pkOps, into: &buf)
        FfiConverterSequenceSequenceString.write(value.merklePaths, into: &buf)
        FfiConverterSequenceUInt64.write(value.leafIndices, into: &buf)
        FfiConverterString.write(value.root, into: &buf)
        FfiConverterSequenceString.write(value.anchorEvals, into: &buf)
        FfiConverterString.write(value.hanchor, into: &buf)
        FfiConverterString.write(value.hSignUserOp, into: &buf)
        FfiConverterString.write(value.random, into: &buf)
        FfiConverterSequenceString.write(value.audHashList, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapProofRequest_lift(_ buf: RustBuffer) throws -> ZkapProofRequest {
    return try FfiConverterTypeZkapProofRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapProofRequest_lower(_ value: ZkapProofRequest) -> RustBuffer {
    return FfiConverterTypeZkapProofRequest.lower(value)
}


public struct ZkapSecret: Equatable, Hashable {
    public var sub: String
    public var iss: String
    public var aud: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(sub: String, iss: String, aud: String) {
        self.sub = sub
        self.iss = iss
        self.aud = aud
    }

    

    
}

#if compiler(>=6)
extension ZkapSecret: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapSecret: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapSecret {
        return
            try ZkapSecret(
                sub: FfiConverterString.read(from: &buf), 
                iss: FfiConverterString.read(from: &buf), 
                aud: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: ZkapSecret, into buf: inout [UInt8]) {
        FfiConverterString.write(value.sub, into: &buf)
        FfiConverterString.write(value.iss, into: &buf)
        FfiConverterString.write(value.aud, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapSecret_lift(_ buf: RustBuffer) throws -> ZkapSecret {
    return try FfiConverterTypeZkapSecret.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapSecret_lower(_ value: ZkapSecret) -> RustBuffer {
    return FfiConverterTypeZkapSecret.lower(value)
}


public enum ZkapError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ApplicationError(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension ZkapError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZkapError: FfiConverterRustBuffer {
    typealias SwiftType = ZkapError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZkapError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ApplicationError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ZkapError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ApplicationError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapError_lift(_ buf: RustBuffer) throws -> ZkapError {
    return try FfiConverterTypeZkapError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZkapError_lower(_ value: ZkapError) -> RustBuffer {
    return FfiConverterTypeZkapError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceUInt64: FfiConverterRustBuffer {
    typealias SwiftType = [UInt64]

    public static func write(_ value: [UInt64], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt64.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt64] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt64]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterUInt64.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeZkapSecret: FfiConverterRustBuffer {
    typealias SwiftType = [ZkapSecret]

    public static func write(_ value: [ZkapSecret], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeZkapSecret.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [ZkapSecret] {
        let len: Int32 = try readInt(&buf)
        var seq = [ZkapSecret]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeZkapSecret.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [[String]]

    public static func write(_ value: [[String]], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterSequenceString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [[String]] {
        let len: Int32 = try readInt(&buf)
        var seq = [[String]]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterSequenceString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Generate a Poseidon threshold anchor from a list of JWT credential secrets.
 */
public func generateAnchor(config: ZkapCircuitConfig, secrets: [ZkapSecret])throws  -> ZkapAnchorResult  {
    return try  FfiConverterTypeZkapAnchorResult_lift(try rustCallWithError(FfiConverterTypeZkapError_lift) {
    uniffi_zkap_uniffi_bindings_fn_func_generate_anchor(
        FfiConverterTypeZkapCircuitConfig_lower(config),
        FfiConverterSequenceTypeZkapSecret.lower(secrets),$0
    )
})
}
/**
 * Compute per-audience hashes and the combined audience-list hash.
 */
public func generateAudHash(config: ZkapCircuitConfig, audList: [String])throws  -> ZkapAudHashResult  {
    return try  FfiConverterTypeZkapAudHashResult_lift(try rustCallWithError(FfiConverterTypeZkapError_lift) {
    uniffi_zkap_uniffi_bindings_fn_func_generate_aud_hash(
        FfiConverterTypeZkapCircuitConfig_lower(config),
        FfiConverterSequenceString.lower(audList),$0
    )
})
}
/**
 * Compute a Poseidon hash of one or more field-element strings (hex or decimal).
 *
 * Returns the result as a 0x-prefixed hex string.
 */
public func generateHash(messages: [String])throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZkapError_lift) {
    uniffi_zkap_uniffi_bindings_fn_func_generate_hash(
        FfiConverterSequenceString.lower(messages),$0
    )
})
}
/**
 * Compute the Merkle leaf hash for an issuer + RSA public-key modulus (base64-encoded).
 *
 * Returns the leaf field element as a 0x-prefixed hex string.
 */
public func generateLeafHash(config: ZkapCircuitConfig, iss: String, pkB64: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeZkapError_lift) {
    uniffi_zkap_uniffi_bindings_fn_func_generate_leaf_hash(
        FfiConverterTypeZkapCircuitConfig_lower(config),
        FfiConverterString.lower(iss),
        FfiConverterString.lower(pkB64),$0
    )
})
}
/**
 * Generate Groth16 proofs from raw user inputs.
 */
public func prove(config: ZkapCircuitConfig, request: ZkapProofRequest)throws  -> ZkapProofOutput  {
    return try  FfiConverterTypeZkapProofOutput_lift(try rustCallWithError(FfiConverterTypeZkapError_lift) {
    uniffi_zkap_uniffi_bindings_fn_func_prove(
        FfiConverterTypeZkapCircuitConfig_lower(config),
        FfiConverterTypeZkapProofRequest_lower(request),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zkap_uniffi_bindings_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_zkap_uniffi_bindings_checksum_func_generate_anchor() != 10088) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zkap_uniffi_bindings_checksum_func_generate_aud_hash() != 42467) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zkap_uniffi_bindings_checksum_func_generate_hash() != 6188) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zkap_uniffi_bindings_checksum_func_generate_leaf_hash() != 28430) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zkap_uniffi_bindings_checksum_func_prove() != 26090) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureZkapUniffiBindingsInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all