// Generated by uniffi-bindgen-react-native
package com.baerae.zkapreactnative

import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.Promise
import com.facebook.react.module.annotations.ReactModule
import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder

@ReactModule(name = ZkapReactNativeModule.NAME)
class ZkapReactNativeModule(reactContext: ReactApplicationContext) :
  NativeZkapReactNativeSpec(reactContext) {

  override fun getName(): String {
    return NAME
  }

  // Two native methods implemented in cpp-adapter.cpp, and ultimately
  // baerae-zkap-react-native.cpp

  external fun nativeInstallRustCrate(runtimePointer: Long, callInvoker: CallInvokerHolder): Boolean
  external fun nativeCleanupRustCrate(runtimePointer: Long): Boolean

  override fun installRustCrate(): Boolean {
    val context = this.reactApplicationContext
    return nativeInstallRustCrate(
      context.javaScriptContextHolder!!.get(),
      context.jsCallInvokerHolder!!
    )
  }

  override fun cleanupRustCrate(): Boolean {
    return nativeCleanupRustCrate(
      this.reactApplicationContext.javaScriptContextHolder!!.get()
    )
  }

  override fun runWitnessInWkWebView(inputJson: String, promise: Promise) {
    promise.reject(
      "zkap-witness-webview-unsupported",
      "runWitnessInWkWebView is only available on iOS"
    )
  }

  companion object {
    const val NAME = "ZkapReactNative"

    init {
      System.loadLibrary("baerae-zkap-react-native")
    }
  }
}
